### ISSUE TITLE
Error 504 in front

### ISSUE THREAD

**Issue by vasiliy-palagin** [LukeTowers/oc-blank-theme#2]
In system eventlogs error - Symfony\Component\Debug\Exception\FatalErrorException: Maximum execution time of 60 seconds exceeded in /var/www/--/data/www/--/vendor/kriswallsmith/assetic/src/Assetic/Asset/FileAsset.php:65

**Comment by LukeTowers** [comment]
@vasiliy-palagin what version of October are you using? There was a circular reference issue that I fixed in the core OctoberCMS less files recently that would probably cause this. Try commenting out `@import october.less` in the theme.less file

**Comment by vasiliy-palagin** [comment]
October 437 version, commenting did not help

**Comment by LukeTowers** [comment]
Comment out this one: https://github.com/LukeTowers/oc-blank-theme/blob/master/assets/less/theme.less#L5

**Comment by vasiliy-palagin** [comment]
Рage loaded without styles

**Comment by LukeTowers** [comment]
Paste your current copy of theme.less

**Comment by vasiliy-palagin** [comment]
```less
//
// Boot dependencies and theme
//

// @import "../vendor/october/boot.less";
@import "theme/boot";

//
// Fonts
//

@import "theme/fonts";

//
// Dependencies
//

@import "../vendor/normalize.css/normalize.less";
@import "../vendor/bootstrap-grid-only/grid.css.less";
@import "../vendor/october/october.less";

//
// Theme Styles
//
@import "theme/animations";
@import "theme/base";
```

**Comment by LukeTowers** [comment]
comment out both october related ones, `october/boot.less` and `october.less`

**Comment by vasiliy-palagin** [comment]
Thanks, everything is good)

**Comment by LukeTowers** [comment]
Good to hear! 

You'll be able to uncomment those lines when https://github.com/octobercms/october/commit/dd6a05bdc4609d64498a5d29f97f7bcaa9ea9c35 makes it to master and you update.
