### ISSUE TITLE
Missing roboto fonts

### ISSUE THREAD

**Issue by amp9020** [LukeTowers/oc-blank-theme#3]
Theme wants to reference Google's Roboto fonts but repo doesn't have the font folder and the Roboto folder (with fonts).

![fonts_missing](https://user-images.githubusercontent.com/16352460/47969452-de323e00-e045-11e8-9adf-c1c903080b10.png)

**Comment by LukeTowers** [comment]
@amp9020 I've checked and the theme doesn't reference those anywhere. This is probably being injected by either your own modifications to the theme or a third party component included in the theme.

**Comment by amp9020** [comment]
Confirmed. it was being injected.  Closing case. thanks.
